### ISSUE TITLE
Restructure manifest and folder structure here

### ISSUE THREAD

**Issue by parkr** [octopress/video-tag#3]
EVERY plugin installed should be in the subdirectory of its name. It will look for:

```text
javascripts/lib/
javascripts/modules/
plugins/
stylesheets/
```

All files in the above directories will be copied (with subdirectory structure preserved within these base directories) into the appropriate Octopress site folders, namespaced into a subdirectory which takes its name from `slug` in the manifest.yml file.

## manifest.yml

```yml
name: "HTML 5 Video"
author: "Brandon Mathis"
description: "A really cool liquid tag that embeds your video in your site."
url: "https://github.com/octopress/video-tag"
documentation: "http://octopress.org/video-tag/"
slug: "video-tag" # subdirectory slug - REQUIRED

source: # REQUIRED if you have source files
  - 
    path:        'source/video-tag/'
    destination: 'assets/video-tag/'
```
